import { CgMenuRight } from 'react-icons/cg';
import { IoCloseSharp } from 'react-icons/io5';
import { HiOutlineCurrencyYen } from 'react-icons/hi';
import { HiOutlineArrowSmRight } from 'react-icons/hi';
import { HiOutlineArrowSmLeft } from 'react-icons/hi';
import { FaArrowCircleUp } from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import { IoReturnUpBack } from 'react-icons/io5';
import { FiSettings } from 'react-icons/fi';
import { IoMdClose } from 'react-icons/io';
import { MdOutlineCancel } from 'react-icons/md';
import LogoImg from './../assets/Logo.png';

export const Menu = CgMenuRight;
export const Close = IoCloseSharp;
export const Currency = HiOutlineCurrencyYen;
export const LeftArrow = HiOutlineArrowSmLeft;
export const RightArrow = HiOutlineArrowSmRight;
export const ArrowScrollTop = FaArrowCircleUp;
export const GoogleIcon = FcGoogle;
export const BackArrow = IoReturnUpBack;
export const SettingsIcon = FiSettings;
export const CloseIcon = IoMdClose;
export const Logo = LogoImg;
