import { CgMenuRight } from 'react-icons/cg';
import { IoCloseSharp } from 'react-icons/io5';
import { HiOutlineCurrencyYen } from 'react-icons/hi';
import { HiOutlineArrowSmRight } from 'react-icons/hi';
import { HiOutlineArrowSmLeft } from 'react-icons/hi';
import { FaArrowCircleUp } from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import { IoReturnUpBack } from 'react-icons/io5';
import { FiSettings } from 'react-icons/fi';
import { IoMdClose } from 'react-icons/io';

import { IoMdAddCircleOutline } from 'react-icons/io';
import { MdToday } from 'react-icons/md';
import { BsCalendarWeek } from 'react-icons/bs';
import { MdCalendarMonth } from 'react-icons/md';
import LogoImg from './../assets/Logo.png';
import { FaRegTrashAlt } from 'react-icons/fa';
import { MdDateRange } from 'react-icons/md';
import { MdCategory } from 'react-icons/md';
import { MdDescription } from 'react-icons/md';
import { FaMoneyBill1Wave } from 'react-icons/fa6';
import { RiAccountPinCircleFill } from 'react-icons/ri';

export const Menu = CgMenuRight;
export const Close = IoCloseSharp;
export const Currency = HiOutlineCurrencyYen;
export const LeftArrow = HiOutlineArrowSmLeft;
export const RightArrow = HiOutlineArrowSmRight;
export const ArrowScrollTop = FaArrowCircleUp;
export const GoogleIcon = FcGoogle;
export const BackArrow = IoReturnUpBack;
export const SettingsIcon = FiSettings;
export const CloseIcon = IoMdClose;
export const Logo = LogoImg;
export const AddIcon = IoMdAddCircleOutline;
export const TrashIcon = FaRegTrashAlt;
export const TodayIcon = MdToday;
export const WeekIcon = BsCalendarWeek;
export const MonthIcon = MdCalendarMonth;
export const DateIcon = MdDateRange;
export const DescriptionIcon = MdDescription;
export const AmountIcon = FaMoneyBill1Wave;
export const AccountIcon = RiAccountPinCircleFill;
export const CategoryIcon = MdCategory;
